site_name: Bonfo - drone configuration management
site_url: https://destos.github.io/bonfo
repo_url: https://github.com/destos/bonfo
repo_name: destos/bonfo
edit_uri: edit/main/docs/
#strict: true
nav:
  - Home: index.md
  - Ideas: ideas.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - CLI: cli.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  logo: assets/logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  name: material
  language: en
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
  - mkdocs-click
plugins:
  - include-markdown
  - git-revision-date:
      enabled_if_env: CI
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - bonfo
extra:
  social:
    # - icon: fontawesome/brands/twitter
    #   # replace with your own tweet link below
    #   link: https://github.com/waynerv/cookiecutter-pypackage
    #   name: Tweet
    # - icon: fontawesome/brands/facebook
    #   # replace with your own facebook link below
    #   link: https://github.com/waynerv/cookiecutter-pypackage
    #   name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/destos/bonfo
      name: Github
    - icon: material/email
      link: "mailto:patrick@forringer.com?subject=Bonfo"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
