from enum import IntEnum


class ArmingdisableflagnamesBF(IntEnum):
    NOGYRO = 0
    FAILSAFE = 1
    RXLOSS = 2
    BADRX = 3
    BOXFAILSAFE = 4
    RUNAWAY = 5
    CRASH = 6
    THROTTLE = 7
    ANGLE = 8
    BOOTGRACE = 9
    NOPREARM = 10
    LOAD = 11
    CALIB = 12
    CLI = 13
    CMS = 14
    BST = 15
    MSP = 16
    PARALYZE = 17
    GPS = 18
    RESCUE_SW = 19
    RPMFILTER = 20
    ARMSWITCH = 21


class ArmingdisableflagnamesInav(IntEnum):
    OK_TO_ARM = 0
    PREVENT_ARMING = 1
    ARMED = 2
    WAS_EVER_ARMED = 3
    BLOCKED_UAV_NOT_LEVEL = 8
    BLOCKED_SENSORS_CALIBRATING = 9
    BLOCKED_SYSTEM_OVERLOADED = 10
    BLOCKED_NAVIGATION_SAFETY = 11
    BLOCKED_COMPASS_NOT_CALIBRATED = 12
    BLOCKED_ACCELEROMETER_NOT_CALIBRATED = 13
    BLOCKED_HARDWARE_FAILURE = 15
    BLOCKED_INVALID_SETTING = 26
